### PR TITLE
added functionality to trash,label,TextEditor,filter,auth

### PR DESCRIPTION
**Pull request by Mandhularajitha**

### CODE REVIEW

**Review by preethasri — APPROVED** [review]
auth functionality working fine .good to merge

**Review by SK02K1 — APPROVED** [review]

**Review by aniketxparihar — APPROVED** [review]
- Code looks really clean
- Liked the Reducers
- Good and on point CSS naming conventions used
- Good Folder Structure 
- Code is modular and well structured
Good to merge!

**Comment by aniketxparihar** [comment]
You have merge conflicts. Resolve them rest looks good

**Comment by Mandhularajitha** [comment]
added functionality

**Pull request merged**
